import {useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {useExperienceMode} from '../../app/ExperienceMode';
import {farmBase,farmModel,farmPairs,farmKey,crops,type Crop,type FarmInput,type FarmResult} from './farmModel';
import {FarmChart,FarmScene} from './FarmFigures';
import './farm.css';
const steps=[
 {name:'提出预测',time:'0–3 分钟',q:'雨量一样，农业用水条件就一样吗？',task:'先预测：雨季晚到 20 天，播期不变，幼苗期供水会不会改变？这里使用原创季节情景，不代表真实地区的气候观测。'},
 {name:'雨热对照',time:'3–8 分钟',q:'同样的总雨量，是否落在作物需要的时候？',task:'固定作物、播期和无补灌，分别记录原时序与晚到 20 天。比较前 20 天缺口，不只看整季总量。'},
 {name:'方案取舍',time:'8–15 分钟',q:'推迟播种、补灌和换作物，各有什么代价？',task:'保留晚到情景。一次只改变播期、补灌或作物中的一项，记录后再比较；低温暴露与水分缺口要一起看。'},
 {name:'证据解释',time:'15–20 分钟',q:'引用证据，解释为什么不存在通用的最优方案。',task:'说明哪些条件相同，哪些条件不同。供水缺口不是减产率；需水少也不等于产量高、收益好。'},
];
const f=(n:number)=>n.toFixed(1);
export default function AgricultureLab(){
 const {isClassroom}=useExperienceMode(),root=useRef<HTMLElement>(null);
 const [step,setStep]=useState(0),[input,setInput]=useState<FarmInput>({...farmBase,delay:20}),[period,setPeriod]=useState(3),[prediction,setPrediction]=useState<string|null>(null),[records,setRecords]=useState<FarmResult[]>([]),[reference,setReference]=useState(false),[answer,setAnswer]=useState<string|null>(null),[notice,setNotice]=useState('');
 const effective=step===1?{...farmBase,delay:input.delay}:input,result=farmModel(effective),base=farmModel({...effective,delay:0}),pairs=farmPairs(records),ready=!!(pairs.base&&pairs.late&&pairs.response);
 const sampled=result.days.slice(period*10,period*10+10),total=(key:'rain'|'deficit'|'irrigation')=>sampled.reduce((s,d)=>s+d[key],0);
 function go(s:number){setStep(s);if(s===2)setInput(i=>({...farmBase,delay:i.delay||20}));requestAnimationFrame(()=>root.current?.scrollIntoView({block:'start',behavior:'instant'}));}
 function change<K extends keyof FarmInput>(key:K,value:FarmInput[K]){setInput(i=>({...i,[key]:value}));}
 function reset(){setStep(0);setInput({...farmBase,delay:20});setPeriod(3);setPrediction(null);setRecords([]);setReference(false);setAnswer(null);setNotice('');}
 function record(){if(records.length<12&&!records.some(r=>farmKey(r.input)===farmKey(result.input))){setRecords(rows=>[...rows,result]);setReference(false);}}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({topic:'GQ-T022',version:'2.0.0',prediction,model:'Original hypothetical seasonal water balance, NOT observation or yield forecast',units:{water:'mm',days:'day offset 0..179',temperature:'C'},records},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='GeoQuest-气候与农业-实验记录.json';a.click();URL.revokeObjectURL(url);}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current?.requestFullscreen();}catch{setNotice('此浏览器未允许全屏，可继续使用课堂布局。');}}
 return <article ref={root} className={`farm-lab farm-step-${step} ${isClassroom?'farm-classroom':''}`}>
 <header className="farm-heading"><div><span>04 / 农业实验室 · 七年级 · 20 分钟探究</span><h1>气候与农业</h1></div><div className="farm-actions"><Link to={isClassroom?'/topics/south-asia-monsoon':'/topics/south-asia-monsoon?mode=classroom'}>{isClassroom?'退出课堂':'课堂展示'}</Link><button onClick={()=>void fullscreen()}>切换全屏</button><button onClick={reset}>重置实验</button></div></header>
 {notice&&<p role="status">{notice}</p>}<nav className="farm-steps" aria-label="农业探究步骤">{steps.map((s,i)=><button key={s.name} aria-current={step===i?'step':undefined} onClick={()=>go(i)}><span>0{i+1}</span>{s.name}<small>{s.time}</small></button>)}</nav>
 <section className="farm-prompt"><h2>{steps[step]!.q}</h2><p>{steps[step]!.task}</p></section>
 {step<3?<div className="farm-board"><div className="farm-visual">{step===0?<><FarmScene/><h2>雨热条件 × 生长日历 × 有限供水</h2><p>先比较降雨发生的时机，再试验应对方案。用同一块地、同一水量账讨论取舍。</p><p className="farm-small">不用“适宜度总分”代替原因分析；当前只探究水分与低温暴露，不评价产量、价格、市场或利润。</p></>:<><div className="farm-chart-legend"><span>蓝：原降雨时序</span><span>赭：当前降雨时序</span></div><FarmChart base={base} result={result} period={period}/><label className="farm-period">查看第 {period*10}–{period*10+9} 天<input aria-label="观察时段" type="range" min="0" max="17" step="1" value={period} onChange={e=>setPeriod(Number(e.target.value))}/></label><div className="farm-presets">{[2,4,8,13].map(p=><button key={p} aria-pressed={period===p} onClick={()=>setPeriod(p)}>第 {p*10}–{p*10+9} 天</button>)}</div><p className="farm-current">此时段：雨 {f(total('rain'))} mm · 缺口 {f(total('deficit'))} mm · 补灌 {f(total('irrigation'))} mm</p></>}</div>
 <aside className="farm-panel" aria-label="农业实验条件与结果">{step===0?<><h2>我的预测</h2>{['总雨量相同，幼苗期也相同','雨来的时机也会影响供水'].map(p=><button className="farm-choice" key={p} aria-pressed={prediction===p} onClick={()=>setPrediction(p)}>{p}</button>)}<p>{prediction?`已预测：${prediction}`:'先说理由，再选择。'}</p><button className="farm-primary" onClick={()=>go(1)}>开始雨热对照 →</button></>:<>
 <fieldset><legend>雨季时序 · 总雨量保持 320 mm</legend>{[0,20,40].map(d=><button key={d} aria-pressed={input.delay===d} onClick={()=>change('delay',d)}>{d===0?'原时序':`晚到 ${d} 天`}</button>)}</fieldset>
 {step===1?<p className="farm-fixed">固定：玉米示意方案 · 第 20 天播种 · 无补灌</p>:<div className="farm-controls"><label>作物示意方案<select aria-label="作物示意方案" value={input.crop} onChange={e=>change('crop',e.target.value as Crop)}>{Object.entries(crops).map(([k,c])=><option key={k} value={k}>{c.label}</option>)}</select></label><label>播种日<select aria-label="播种日" value={input.sow} onChange={e=>change('sow',Number(e.target.value))}>{[20,40,60].map(s=><option key={s} value={s}>第 {s} 天</option>)}</select></label><label>可用净补灌总量<select aria-label="补灌总量" value={input.irrigation} onChange={e=>change('irrigation',Number(e.target.value))}><option value="0">0 mm</option><option value="60">60 mm（有限预算）</option></select></label><button onClick={()=>setInput({...farmBase,delay:input.delay})}>恢复同雨季基准方案</button></div>}
 <section className="farm-readings"><h3>整季结果 · 模型值</h3><div><span>播后前 20 天缺口</span><strong>{f(result.earlyDeficit)} mm</strong></div><div><span>整季供水缺口</span><strong>{f(result.deficit)} mm</strong></div><div><span>实际净补灌</span><strong>{f(result.irrigated)} / {effective.irrigation} mm</strong></div><div><span>低于 15°C 的生长期</span><strong>{result.coldDays} 天</strong></div></section>
 <p className="farm-small">生长期 {crops[effective.crop].days} 天，结束于第 {result.harvest} 天。温度阈值和需水均为教学假设，不是作物适生标准。</p><button className="farm-primary" disabled={records.length>=12||records.some(r=>farmKey(r.input)===farmKey(result.input))} onClick={record}>{records.some(r=>farmKey(r.input)===farmKey(result.input))?'已记录此情景':'记录整季结果'}</button><p className="farm-record-status" role="status">已记录 {records.length} / 12 条 · {prediction?`原预测：${prediction}`:'条件与结果一起保存'}</p></>}</aside></div>:<div className="farm-synthesis"><section className="farm-notebook"><h2>我的农业证据 <small>{records.length} / 12</small></h2>{records.length?<><div className="farm-table-scroll"><table><caption>同一块假设农田的整季记录；水量单位 mm</caption><thead><tr><th>晚到 / 播日</th><th>作物</th><th>补灌</th><th>早期缺口</th><th>整季缺口</th><th>低温天数</th><th>操作</th></tr></thead><tbody>{records.map(r=><tr key={farmKey(r.input)}><td>{r.input.delay} / {r.input.sow}</td><td>{crops[r.input.crop].label}</td><td>{f(r.irrigated)}</td><td>{f(r.earlyDeficit)}</td><td>{f(r.deficit)}</td><td>{r.coldDays}</td><td><button aria-label={`移除 ${farmKey(r.input)} 记录`} onClick={()=>{setRecords(rows=>rows.filter(s=>farmKey(s.input)!==farmKey(r.input)));setReference(false);}}>移除</button></td></tr>)}</tbody></table></div><button onClick={download}>导出实验记录 JSON ↓</button></>:<p>先记录原时序和晚到情景，再记录一种应对方案。</p>}<p className="farm-small">只在本页保存，切换模式保留，刷新清除。</p></section><section className="farm-explanation"><h2>先解释，再看参考</h2><p>{pairs.base&&pairs.late?'✓':'○'} 原时序与晚到的同条件对照</p><p>{pairs.response?'✓':'○'} 相同晚到天数下的一项应对改变</p><button disabled={!ready} aria-expanded={reference&&ready} onClick={()=>setReference(v=>!v)}>{reference?'收起讨论参考':'显示讨论参考'}</button>{reference&&ready&&pairs.base&&pairs.late&&pairs.response&&<div className="farm-answer"><p>雨量同为 320 mm，但播后前 20 天缺口由 {f(pairs.base.earlyDeficit)} 变为 {f(pairs.late.earlyDeficit)} mm。整季合计可能相同，时段内的供水仍可能不同。</p><p>应对方案：早期缺口 {f(pairs.response.earlyDeficit)} mm，整季缺口 {f(pairs.response.deficit)} mm，净补灌 {f(pairs.response.irrigated)} mm，低温暴露 {pairs.response.coldDays} 天。要结合用水代价、生长期与模型边界解释。</p><p>这是季节时序的反事实实验，不能据此断言某地必然减产或长期气候已经改变；作物更换的产量与市场代价不在模型中。</p></div>}<fieldset className="farm-transfer"><legend>离堂一问：供水缺口为零，能保证丰收吗？</legend>{['不能，还受其他条件影响','能，水够就一定丰收'].map(a=><button key={a} aria-pressed={answer===a} onClick={()=>setAnswer(a)}>{a}</button>)}{answer&&<p role="status">{answer.startsWith('不能')?'对。还需品种、土壤、病虫害等证据，不能把供水模型当产量预报。':'请检查模型范围：这里只核对供水与低温暴露，没有预测产量。'}</p>}</fieldset></section></div>}
 <details className="farm-method"><summary>模型、来源与适用范围</summary><p>全部气温、雨型与作物系数为原创教学情景，不是印度或其他地区的观测与气候平均值。第 0 天为任意季节起点；完整 180 天雨量 320 mm，延后 0/20/40 天保留尾段，总量不变。延迟一次雨季不是长期气候变化。</p><p>按天计算根区水量：初始可用水 20 mm，上限 60 mm；80%降雨作为根区入水，超容量部分外排，其余20%不进入根区；先入水再耗水，不计休耕期蒸发、地下水、田间输水损失。缺水时按剩余预算补足日需水；净补灌总量不超过 60 mm。初存水 + 根区入水 + 补灌 = 实际耗水 + 末存水 + 外排。</p><p>玉米示意生长期100天，四阶段各25天，日需水2/4/5/3 mm；谷子示意80天，四阶段各20天，日需水1.5/2.5/3/2 mm。不是推荐品种或FAO校准参数。低于15°C天数是讨论播期取舍的统一教学指标，不代表两作物的实际损伤阈值，不按它扣减产量。</p><p>参考 <a href="https://www.fao.org/aquastat/en/data-analysis/irrig-water-use/irrig-water-requirement/">FAO AQUASTAT 作物与灌溉需水原理</a>和<a href="https://www.fao.org/4/s2022e/s2022e08.htm">FAO 有效降雨与灌溉需水</a>（2026-09-19核验）。仅参考原理，未复制图像或用真实地区名称包装假设参数。SVG原创，无外部API或持续动画。</p></details>
 </article>;
}
