import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import fg from "fast-glob";
import { parse } from "yaml";
import { topicManifestSourceSchema } from "../src/content/schema.ts";
import { toPublicTopicManifest } from "../src/content/publicManifest.ts";
import type { PublicTopicManifest } from "../src/domain/topic.ts";
import { selectedGroups } from '../src/topics/selected/selection.ts';

const projectRoot = process.cwd();
const manifestFiles = await fg("content/topics/*/manifest.yaml", {
  cwd: projectRoot,
  absolute: true,
  onlyFiles: true,
});

if (manifestFiles.length === 0) {
  throw new Error("没有找到可编译的主题 manifest");
}

const manifests: PublicTopicManifest[] = [];
for (const file of manifestFiles.sort()) {
  const parsed = topicManifestSourceSchema.parse(parse(await readFile(file, "utf8")));
  manifests.push(toPublicTopicManifest(parsed));
}

const generatedDirectory = path.join(projectRoot, "src/generated");
const generatedFile = path.join(generatedDirectory, "topic-manifests.ts");
const publishedGeneratedFile = path.join(
  generatedDirectory,
  "published-topic-manifests.ts",
);
const publishedRegistryFile = path.join(
  generatedDirectory,
  "published-topic-registry.tsx",
);
const publishedBodyRegistryFile = path.join(
  generatedDirectory,
  "published-topic-body-registry.tsx",
);

function manifestModule(values: typeof manifests): string {
  return `/* This file is generated by scripts/compile-content.ts. */
import type { PublicTopicManifest } from "../domain/topic";

export const topicManifests: readonly PublicTopicManifest[] = ${JSON.stringify(values, null, 2)};

export function getPublicTopicManifest(slug: string): PublicTopicManifest | undefined {
  return topicManifests.find((topic) => topic.slug === slug);
}
`;
}

type InteractiveModule = {
  path: string;
  exportName?: string;
};

const interactiveModules: Readonly<Record<string, InteractiveModule>> = {
  ...Object.fromEntries(selectedGroups.reading.map(slug => [slug, {path: '../topics/selected/ReadingLab'}])),
  ...Object.fromEntries(selectedGroups.process.map(slug => [slug, {path: '../topics/selected/ProcessLab'}])),
  ...Object.fromEntries(selectedGroups.decisions.map(slug => [slug, {path: '../topics/selected/DecisionLab'}])),
  "earth-motion-lab": { path: "../topics/earth/EarthSunLab" },
  "contour-rescue": { path: "../topics/terrain/TerrainLab" },
  "world-population-map": { path: "../topics/population/PopulationLab" },
  "south-asia-monsoon": { path: "../topics/agriculture/AgricultureLab" },
  "us-farm-belt": {
    path: "../topics/interactives",
    exportName: "UsFarmBelt",
  },
  "china-terrain-steps": {
    path: "../topics/interactives",
    exportName: "ChinaTerrainSteps",
  },
  "lake-restoration": {
    path: "../topics/interactives",
    exportName: "LakeRestoration",
  },
  "china-farm-choice": {
    path: "../topics/interactives",
    exportName: "ChinaFarmChoice",
  },
  "yangtze-belt": {
    path: "../topics/interactives",
    exportName: "YangtzeBelt",
  },
  "loess-soil-water": { path: "../topics/watershed/WatershedLab" },
};

const publishedManifests = manifests.filter((topic) => topic.status === "已发布");
for (const topic of publishedManifests) {
  if (!Object.hasOwn(interactiveModules, topic.slug)) {
    throw new Error(`已发布主题 ${topic.slug} 没有注册互动组件`);
  }
}

function interactiveImport(module: InteractiveModule): string {
  const importExpression = `lazy(() => import(${JSON.stringify(module.path)})`;
  return module.exportName
    ? `${importExpression}.then((module) => ({ default: module.${module.exportName} })))`
    : `${importExpression})`;
}

const publishedRegistryEntries = publishedManifests
  .map((topic) => {
    const module = interactiveModules[topic.slug]!;
    return `  ${JSON.stringify(topic.slug)}: ${interactiveImport(module)},`;
  })
  .join("\n");
const registryImport = publishedManifests.length > 0
  ? 'import { lazy, type ComponentType } from "react";'
  : 'import type { ComponentType } from "react";';
const publishedRegistry = `/* This file is generated by scripts/compile-content.ts. */
${registryImport}

const registry: Record<string, ComponentType> = {
${publishedRegistryEntries}
};

export function getTopicInteractive(slug: string): ComponentType | undefined {
  return registry[slug];
}

export const interactiveSlugs = Object.freeze(Object.keys(registry));
`;

const publishedBodyEntries = publishedManifests
  .map(
    (topic) =>
      `  ${JSON.stringify(topic.slug)}: lazy(() => import(${JSON.stringify(`../../content/topics/${topic.slug}/index.mdx`)})),`,
  )
  .join("\n");
const publishedBodyRegistry = `/* This file is generated by scripts/compile-content.ts. */
${registryImport}

const registry: Record<string, ComponentType> = {
${publishedBodyEntries}
};

export function getTopicBody(slug: string): ComponentType | undefined {
  return registry[slug];
}

export const topicBodySlugs = Object.freeze(Object.keys(registry));
`;

await mkdir(generatedDirectory, { recursive: true });
await Promise.all([
  writeFile(generatedFile, manifestModule(manifests), "utf8"),
  writeFile(
    publishedGeneratedFile,
    manifestModule(publishedManifests),
    "utf8",
  ),
  writeFile(publishedRegistryFile, publishedRegistry, "utf8"),
  writeFile(publishedBodyRegistryFile, publishedBodyRegistry, "utf8"),
]);
console.log(
  `主题公共投影已生成：开发 ${manifests.length} 个，生产 ${publishedManifests.length} 个`,
);
