import {useEffect,useMemo,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {useExperienceMode} from '../../app/ExperienceMode';
import {runWater,scenarioKey,evidencePairs,capacityLabel,type WaterResult} from './waterModel';
import {BasinFigure,SlopeFigure,Hydrograph,WaterBudget} from './WaterFigures';
import './water.css';
const stages=[
  {name:'提出预测',time:'0–3 分钟',question:'一场雨，从山坡到下游，会经历什么？',task:'沿着坡面、支流和出口追踪雨水。预测：增加植被覆盖，雨水全部留在山上了吗？'},
  {name:'坡面对照',time:'3–8 分钟',question:'同一场雨，植被怎样改变水与土的去向？',task:'只改变覆盖率，比较 20% 与 80% 两个坡面。先读水量，再看相对侵蚀，分别记录两种情景。'},
  {name:'流域调蓄',time:'8–15 分钟',question:'下游流量峰值变低，是水消失了吗？',task:'保持降雨和覆盖不变，对照有无滞蓄。拖动时间到雨停之后，核对流出水量与暂存水量。'},
  {name:'证据解释',time:'15–20 分钟',question:'用两组对照，解释保土与调蓄的不同作用。',task:'说明改变与保持的条件。区分坡面产流、相对侵蚀、下游峰值和累计水量，再解释模型不能回答什么。'},
];
const fmt=(n:number)=>Math.round(n).toLocaleString('en-US');
export default function WatershedLab(){
  const {isClassroom}=useExperienceMode();const root=useRef<HTMLElement>(null);
  const [step,setStep]=useState(0),[rain,setRain]=useState(30),[cover,setCover]=useState(20),[capacity,setCapacity]=useState(12000),[index,setIndex]=useState(0);
  const [horizon,setHorizon]=useState(120);
  const [playing,setPlaying]=useState(false),[reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
  const [prediction,setPrediction]=useState<string|null>(null),[records,setRecords]=useState<WaterResult[]>([]),[reference,setReference]=useState(false),[answer,setAnswer]=useState<string|null>(null);
  const [focus,setFocus]=useState('坡面'),[full,setFull]=useState(false),[message,setMessage]=useState('');
  const direct=useMemo(()=>runWater({rain,cover,capacity:0}),[rain,cover]);
  const result=useMemo(()=>runWater({rain,cover,capacity:step>=2?capacity:0}),[rain,cover,capacity,step]);
  const low=useMemo(()=>runWater({rain,cover:20,capacity:0}),[rain]),high=useMemo(()=>runWater({rain,cover:80,capacity:0}),[rain]);
  const frame=result.frames[index]!,pairs=evidencePairs(records),ready=!!(pairs.high&&pairs.retained),lesson=stages[step]!;
  const already=records.some(r=>scenarioKey(r.input)===scenarioKey(result.input));
  useEffect(()=>{
    const media=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{setReduced(media.matches);if(media.matches)setPlaying(false);};
    const hide=()=>{if(document.hidden)setPlaying(false);};const fullscreen=()=>setFull(document.fullscreenElement===root.current);
    media.addEventListener('change',change);document.addEventListener('visibilitychange',hide);document.addEventListener('fullscreenchange',fullscreen);
    return()=>{media.removeEventListener('change',change);document.removeEventListener('visibilitychange',hide);document.removeEventListener('fullscreenchange',fullscreen);};
  },[]);
  useEffect(()=>{if(!playing||reduced||index>=48)return;const timer=setInterval(()=>setIndex(i=>{if(i>=48)return 48;return i+1;}),450);return()=>clearInterval(timer);},[playing,reduced,index]);
  const running=playing&&index<48;
  const chartHorizon=index>12?480:horizon;
  function go(s:number){setPlaying(false);setStep(s);setIndex(s===1?6:s===2?3:0);requestAnimationFrame(()=>root.current?.scrollIntoView({behavior:'instant',block:'start'}));}
  function time(i:number){setPlaying(false);setIndex(i);if(i>12)setHorizon(480);}
  function reset(){setStep(0);setHorizon(120);setRain(30);setCover(20);setCapacity(12000);setIndex(0);setPlaying(false);setPrediction(null);setRecords([]);setReference(false);setAnswer(null);setFocus('坡面');setMessage('');}
  function record(){if(already||records.length>=12)return;setRecords(rows=>[...rows,result]);setReference(false);}
  async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current?.requestFullscreen();}catch{setMessage('此浏览器未允许全屏，可继续使用课堂布局。');}}
  function download(){const data={topic:'GQ-T065',version:'2.0.0',prediction,areaM2:1000000,intervalSeconds:600,initialStorageM3:0,units:{rain:'mm',infiltration:'mm',runoff:'m3',peak:'m3/s (10-minute mean)',storage:'m3',discharged:'m3',erosion:'dimensionless; baseline 100'},records};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='GeoQuest-水土与流域-实验记录.json';a.click();URL.revokeObjectURL(url);}
  return <article ref={root} className={`water-lab water-step-${step} ${isClassroom?'water-classroom':''}`}>
    <header className="water-heading"><div><span>03 / 水土实验室 · 八年级 · 20 分钟探究</span><h1>水土与流域</h1></div><div className="water-actions"><Link to={isClassroom?'/topics/loess-soil-water':'/topics/loess-soil-water?mode=classroom'}>{isClassroom?'退出课堂':'课堂展示'}</Link><button onClick={()=>void fullscreen()}>{full?'退出全屏':'全屏投影'}</button><button onClick={reset}>重置实验</button></div></header>
    {message&&<p role="status">{message}</p>}
    <nav className="water-steps" aria-label="水土探究步骤">{stages.map((s,i)=><button key={s.name} aria-current={step===i?'step':undefined} onClick={()=>go(i)}><span>0{i+1}</span>{s.name}<small>{s.time}</small></button>)}</nav>
    <section className="water-prompt" aria-label="本环节任务"><h2>{lesson.question}</h2><p>{lesson.task}</p></section>
    {step<3?<div className="water-board"><div className="water-visual">
      {step===1?<><div className="water-figure-title"><strong>同雨、同土、同坡 · 两坡并排看</strong><span>同一尺度 · 示意图</span></div><div className="water-slopes"><SlopeFigure result={low} frame={low.frames[index]!} label="A 坡"/><SlopeFigure result={high} frame={high.frames[index]!} label="B 坡"/></div><div className="water-slope-budgets"><WaterBudget rain={low.frames[index]!.rainfall} infiltration={low.frames[index]!.infiltration} runoff={low.frames[index]!.runoff}/><WaterBudget rain={high.frames[index]!.rainfall} infiltration={high.frames[index]!.infiltration} runoff={high.frames[index]!.runoff}/></div><p className="water-caption">深绿：入渗 · 蓝色：地表径流；均按 1 km²面积换算。雨滴、坡形与泥沙颗粒为示意，不代表实测。</p></>:<><BasinFigure result={result} frame={frame} focus={focus}/><p className="water-mobile-note">虚线：分水岭 · 圆形区域：滞蓄区</p><div className="water-focus" aria-label="追踪雨水位置">{['坡面','滞蓄区','出口'].map(f=><button key={f} aria-pressed={focus===f} onClick={()=>setFocus(f)}>{f}</button>)}<span>{focus==='坡面'?'入渗的水进入土壤；未入渗部分汇入支流。':focus==='滞蓄区'?'暂存量会变化；蓄满后还有溢流。':'出口流量是每秒流过的水量，不等于累计水量。'}</span></div>{step===2?<><div className="water-chart-legend"><span>┄ 无滞蓄</span><span>━ 当前方案</span><div>{[120,480].map(h=><button key={h} aria-pressed={chartHorizon===h} onClick={()=>{setHorizon(h);if(h===120&&index>12)time(12);}}>{h===120?'前 2 小时':'完整 8 小时'}</button>)}</div></div><Hydrograph direct={direct} stored={result} index={index} horizon={chartHorizon}/><p className="water-mobile-note">纵轴：流量（m³/s）· 横轴：分钟</p></>:<div className="water-intro-note"><h3>先看坡面，再看整个流域。</h3><p>同一场雨中，入渗、地表径流和暂存都有去向。我们用两组对照，把水量变化与流量过程分开。</p><p>原创理想实验，不对应具体河流，不提供洪水预报。</p></div>}</>}
      {step>0&&<div className="water-timeline"><label>观察时间 <output>{index*10} 分钟 · {index===0?'尚未降雨':index<6?'降雨中':index===6?'降雨结束时':'雨已停'}</output><input aria-label="观察时间" type="range" min="0" max="48" step="1" value={index} onChange={e=>time(Number(e.target.value))}/></label><div>{[0,30,60,120,480].map(m=><button key={m} aria-pressed={index*10===m} onClick={()=>time(m/10)}>{m===480?'8 小时':`${m} 分`}</button>)}<button disabled={reduced} onClick={()=>{if(index===48)setIndex(0);setPlaying(!running);}}>{running?'暂停过程':'播放过程'}</button></div>{reduced&&<small>已开启减少动态效果，请用时刻按钮观察。</small>}</div>}
    </div><aside className="water-panel" aria-label="实验条件与证据">
      {step===0?<><span className="water-kicker">我的预测</span><h2>覆盖增加后，<br/>雨水会全部留下吗？</h2>{['全部留下，不再产流','仍会产流，但分配改变'].map(p=><button className="water-choice" key={p} aria-pressed={prediction===p} onClick={()=>setPrediction(p)}>{p}</button>)}<p>{prediction?`已预测：${prediction}。用实验检验。`:'先说理由，再选择。'}</p><button className="water-primary" onClick={()=>go(1)}>开始坡面对照 →</button><p className="water-small">默认总雨量 30 mm，历时 1 小时；面积 1 km²，坡度与土壤保持不变。</p></>:<>
      <div className="water-controls"><label>同一场雨<select aria-label="总雨量" value={rain} onChange={e=>{setRain(Number(e.target.value));setPlaying(false);}}><option value="30">30 mm / 1 小时</option><option value="60">60 mm / 1 小时</option></select></label><fieldset><legend>植被覆盖</legend>{[20,80].map(c=><button key={c} aria-pressed={cover===c} onClick={()=>{setCover(c);setPlaying(false);}}>{c}%{step===1?(c===20?' A 坡':' B 坡'):''}</button>)}</fieldset></div>
      {step===2&&<fieldset className="water-storage-control"><legend>可用滞蓄空间 · 初始为空</legend>{[0,3000,12000].map(c=><button key={c} aria-pressed={capacity===c} onClick={()=>{setCapacity(c);setPlaying(false);}}>{c===0?'无滞蓄':`${c/1000} 千m³`}</button>)}</fieldset>}
      <section className="water-readings" aria-label="当前时刻读数"><h3>第 {index*10} 分钟 · 当前读数</h3>{step===1?<><div><span>累计雨量</span><strong>{frame.rainfall.toFixed(1)} mm</strong></div><div><span>累计入渗</span><strong>{frame.infiltration.toFixed(1)} mm</strong></div><div><span>累计坡面产流</span><strong>{fmt(frame.runoff)} m³</strong></div></>:<><div><span>入流 / 出流</span><strong>{frame.inflow.toFixed(2)} / {frame.outflow.toFixed(2)} m³/s</strong></div><div><span>暂存水量</span><strong>{fmt(frame.storage)} m³</strong></div><div><span>累计流出</span><strong>{fmt(frame.discharged)} m³</strong></div><p className="water-small">水量账：{fmt(frame.runoff)} 产流 = {fmt(frame.discharged)} 流出 + {fmt(frame.storage)} 暂存（m³，显示值取整）</p>{frame.spill>0&&<p className="water-spill" role="status">本时段已蓄满，有 {fmt(frame.spill)} m³ 溢流，已计入出流。</p>}</>}</section>
      <section className="water-event"><h3>整场结果 · 用于记录</h3>{step===1?<><p>产流 <strong>{fmt(result.runoff)} m³</strong> · 入渗 <strong>{result.infiltration.toFixed(1)} mm</strong></p><p>相对侵蚀 <strong>{result.erosion.toFixed(1)}</strong> <small>（基准为 100，无量纲）</small></p></>:<><p>峰值 <strong>{result.peak.toFixed(2)} m³/s</strong> · 出现在 <strong>{result.peakMinute-10}–{result.peakMinute} 分钟</strong></p><p>至 8 小时：流出 {fmt(result.discharged)} + 暂存 {fmt(result.storage)} = 产流 {fmt(result.runoff)} m³</p></>}</section>
      <button className="water-primary" disabled={already||records.length>=12} onClick={record}>{already?'已记录此情景':'记录整场结果'}</button><p className="water-record-status" role="status">已记录 {records.length} / 12 条 · 改变条件不会覆盖记录</p><p className="water-small">{step===1?'侵蚀指数是原创趋势假设，不是吨数或实测减沙率。':'本环节只路由地表径流，不计算基流、蒸发与泥沙沉降。'}{prediction&&` 原预测：${prediction}`}</p></>}
    </aside></div>:<section className="water-synthesis"><div className="water-notebook"><h2>我的实验记录 <small>{records.length} / 12</small></h2>{records.length?<><div className="water-table-scroll"><table><caption>整场条件与结果；暂存和流出截至 8 小时</caption><thead><tr><th>雨量 / 覆盖</th><th>滞蓄</th><th>产流 m³</th><th>侵蚀指数</th><th>峰值 m³/s</th><th>流出 / 暂存 m³</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{records.map(r=><tr key={scenarioKey(r.input)}><th scope="row">{r.input.rain} mm / {r.input.cover}%</th><td>{capacityLabel(r.input.capacity)}</td><td>{fmt(r.runoff)}</td><td>{r.erosion.toFixed(1)}</td><td>{r.peak.toFixed(2)}</td><td>{fmt(r.discharged)} / {fmt(r.storage)}</td><td><button aria-label={`移除 ${scenarioKey(r.input)} 记录`} onClick={()=>{setRecords(rows=>rows.filter(s=>scenarioKey(s.input)!==scenarioKey(r.input)));setReference(false);}}>移除</button></td></tr>)}</tbody></table></div><button onClick={download}>导出实验记录 JSON ↓</button></>:<p>还没有证据。回到坡面对照，记录 20% 与 80% 覆盖的结果。</p>}<p className="water-small">记录只留在本页，切换课堂模式保留，刷新清除；不上传学习记录。</p></div><div className="water-explanation"><h2>先解释，再看参考</h2><ul><li>{pairs.high?'✓':'○'} 同雨量、无滞蓄，比较两种覆盖</li><li>{pairs.retained?'✓':'○'} 同雨量、同覆盖，比较有无滞蓄</li></ul><p>“保持……不变，只改变……，从……读出……。这不能说明……。”</p><button disabled={!ready} aria-expanded={reference&&ready} onClick={()=>setReference(v=>!v)}>{reference?'收起讨论参考':'显示讨论参考'}</button>{!ready&&<p className="water-small">两组有效对照齐全后可展开；无需完成全部变量才允许探究。</p>}{reference&&ready&&pairs.low&&pairs.high&&pairs.direct&&pairs.retained&&<div className="water-answer"><p>{pairs.low.input.rain} mm 降雨、无滞蓄时，覆盖从 20% 到 80%，坡面产流由 {fmt(pairs.low.runoff)} 降为 {fmt(pairs.high.runoff)} m³；这是本模型的入渗与覆盖假设，不能当作通用实测比例。</p><p>{pairs.direct.input.rain} mm、覆盖 {pairs.direct.input.cover}% 时，增加 {pairs.retained.input.capacity/1000} 千m³滞蓄，峰值从 {pairs.direct.peak.toFixed(2)} 变为 {pairs.retained.peak.toFixed(2)} m³/s；坡面总产流仍是 {fmt(pairs.direct.runoff)} m³。雨后水继续流出，暂存的水没有消失。</p><p>增覆盖作用于坡面产流和侵蚀；滞蓄改变径流的时间分配。现实效果还受土壤含水量、雨型、容量和河网等条件制约，不能保证不会洪涝。</p></div>}<fieldset className="water-transfer"><legend>离堂一问：雨停后下游仍有水流，可能是什么原因？</legend>{['滞蓄区仍在释放暂存水','说明模型凭空产生了水'].map(a=><button key={a} aria-pressed={answer===a} onClick={()=>setAnswer(a)}>{a}</button>)}{answer&&<p role="status">{answer.startsWith('滞蓄')?'对。回到 120 分钟，检查暂存量与累计流出是否守恒。':'先核对水量账：之前暂存的水可以在雨停后继续流出。'}</p>}</fieldset></div></section>}
    <details className="water-method"><summary>模型、来源与适用范围</summary><p>这是原创概念模型，不是黄土高原或某条河流的预报。面积固定为 1 km²，土壤、坡度、坡长保持不变，降雨均匀覆盖；1 mm 在该面积上相当于 1000 m³。历时 1 小时，6 个十分钟雨强依次为 12、24、60、48、24、12 mm/h，总计 30 mm；60 mm 情景把各段雨强加倍。</p><p>入渗能力假设为 6 + 18 × 覆盖比例（mm/h），每时段实际入渗不超过雨强；未入渗部分为地表径流。忽略冠层截留、地表积水和土壤饱和变化；入渗并不等于永久留在坡上。本模型只路由地表径流，入渗后可能形成的地下水与基流不在范围内。</p><p>相对侵蚀 = 100 ×（产流 / 20400 m³）×（未覆盖比例² / 0.64）。这是明确公开的方向性教学假设，基准为 30 mm、20% 覆盖、无滞蓄时的 100；未经实测校准，不是 RUSLE，不能换算泥沙吨数、实际减沙率或水质。</p><p>流域滞蓄使用初始为空的理想线性蓄水池，响应时间 1 小时，每 10 分钟按恒定入流解析求解水量平衡，超容量部分作为溢流加入出流。没有河道传播、真实库容曲线、闸门调度、蒸发、渗漏或沉沙；峰值为十分钟时段平均值，非瞬时峰值。图形不按地形与库容比例绘制，容量填充只表示储量占比。8 小时后仍有少量暂存水，不能当作减少的水量。</p><p>事实与方法参考：<a href="https://www.usgs.gov/water-science-school/science/surface-runoff-and-water-cycle">USGS 地表径流与水循环</a>、<a href="https://www.nrcs.usda.gov/conservation-basics/soil/soil-health/cover-crops-for-soil-health">USDA 覆盖与土壤健康</a>、<a href="https://nepis.epa.gov/Exe/ZyPURL.cgi?Dockey=2000D1L8.TXT">EPA 雨洪滞蓄设计原理</a>。只参考原理，不复制图片；模型系数为原创假设。所有 SVG 原创、自托管，不依赖 WebGL、地图或外部教学 API。</p></details>
  </article>;
}
